# Generated by Django 5.0 on 2024-04-06 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engSubject', models.CharField(max_length=200, null=True)),
                ('engContent', models.TextField(null=True)),
                ('korSubject', models.CharField(max_length=200, null=True)),
                ('korContent', models.TextField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('voter', models.ManyToManyField(related_name='voter_AIparagraph', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('isTheSame', models.BooleanField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('errCheckedStr', models.TextField(null=True)),
                ('ai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ias.ai')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_input', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ManyToManyField(related_name='voter_input', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
