# Generated by Django 5.0 on 2024-05-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai",
            name="week",
            field=models.IntegerField(null=True),
        ),
    ]
