# Generated by Django 5.0 on 2024-05-19 04:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ias", "0002_ai_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ai",
            name="week",
        ),
    ]
