# Generated by Django 4.0.3 on 2024-03-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0003_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
