# Generated by Django 5.0 on 2024-04-02 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0007_article_modify_date_input_modify_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='voter',
            field=models.ManyToManyField(related_name='voter_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='input',
            name='voter',
            field=models.ManyToManyField(related_name='voter_input', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='input',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_input', to=settings.AUTH_USER_MODEL),
        ),
    ]
