# Generated by Django 5.0 on 2024-04-04 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0009_input_errcheckedstr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIparagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('voter', models.ManyToManyField(related_name='voter_AIparagraph', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
