# Generated by Django 5.0 on 2024-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0011_rename_aiparagraph_ai'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIandArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
