# Generated by Django 5.0 on 2024-04-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0012_aiandarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AIandArticle',
            new_name='Material',
        ),
    ]
