# Generated by Django 5.0 on 2024-04-04 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0013_rename_aiandarticle_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai',
            name='voter',
            field=models.ManyToManyField(related_name='voter_ai', to=settings.AUTH_USER_MODEL),
        ),
    ]
