# Generated by Django 5.0 on 2024-04-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0014_alter_ai_voter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RemoveField(
            model_name='input',
            name='article',
        ),
        migrations.AddField(
            model_name='input',
            name='ai',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ias.ai'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ai',
            name='voter',
            field=models.ManyToManyField(related_name='voter_AIparagraph', to=settings.AUTH_USER_MODEL),
        ),
    ]
