# Generated by Django 5.0 on 2024-04-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0015_delete_material_remove_input_article_input_ai_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
