# Generated by Django 5.0 on 2024-04-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ias', '0016_delete_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai',
            old_name='content',
            new_name='engContent',
        ),
        migrations.RenameField(
            model_name='ai',
            old_name='subject',
            new_name='engSubject',
        ),
        migrations.AddField(
            model_name='ai',
            name='korContent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ai',
            name='korSubject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
