# Generated by Django 5.0 on 2024-05-15 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opinion", models.TextField(null=True)),
                ("create_date", models.DateTimeField(null=True)),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                (
                    "ai",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ias.ai"
                    ),
                ),
                (
                    "voter",
                    models.ManyToManyField(
                        related_name="voter_Opinion", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
